name: Release - Windows MSI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-msi:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5

      - name: Install WiX Toolset 3.11
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe" -OutFile "wix311.exe"
          Start-Process -FilePath "wix311.exe" -Args "/quiet" -Wait
          echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build Windows MSI
        working-directory: scs2-session-visualizer-jfx
        run: gradle buildWindowsMsiPackage --no-daemon

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: SCS2 ${{ github.ref_name }}
          files: scs2-session-visualizer-jfx/deployment/windows/*.msi
          generate_release_notes: true
